"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os
from dotenv import load_dotenv
import firebase_admin
from firebase_admin import credentials


BASE_DIR = Path(__file__).resolve().parent.parent  # 프로젝트 루트
load_dotenv(BASE_DIR / ".env")

FIREBASE_PROJECT_ID = os.getenv("FIREBASE_PROJECT_ID")
FIREBASE_CREDENTIALS_PATH = os.getenv("FIREBASE_CREDENTIALS_PATH")

# Firebase 초기화 - secrets 폴더에서 자격 증명 파일 찾기
firebase_credential_candidates = [
    BASE_DIR / "secrets" / "sams-295be-firebase-adminsdk-fbsvc-768b33733b.json"
]

firebase_initialized = False
for credential_path in firebase_credential_candidates:
    if os.path.exists(credential_path):
        try:
            cred = credentials.Certificate(str(credential_path))
            if not firebase_admin._apps:
                # 파일명에서 프로젝트 ID 추출
                if "sams-295be" in str(credential_path):
                    project_id = "sams-295be"
                elif "sams-e1b60" in str(credential_path):
                    project_id = "sams-e1b60"
                else:
                    project_id = "sams-295be"  # 기본값
                
                firebase_admin.initialize_app(cred, {"projectId": project_id})
                print(f"✅ Firebase 초기화 성공! ({credential_path.name})")
                firebase_initialized = True
                break
        except Exception as e:
            print(f"❌ Firebase 초기화 실패 ({credential_path.name}): {e}")
            continue

if not firebase_initialized:
    print("⚠️ Firebase 자격 증명 파일을 찾을 수 없습니다. 개발 모드로 실행됩니다.")
# 프로젝트 내부 경로는 이렇게 생성합니다: BASE_DIR / '하위디렉토리'.
BASE_DIR = Path(__file__).resolve().parent.parent


# 빠른 시작 개발 설정 - 운영 환경에는 부적합
# 배포 체크리스트 참조: https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# 보안 경고: 운영 환경에선 비밀키를 반드시 비공개로 유지하세요!
SECRET_KEY = 'django-insecure-5vx-0u!$^+pm8ns3njcc2ni_4r6#nxx)be(s@t&ofw1fthk0i^'

# 보안 경고: 운영 환경에서는 DEBUG 모드를 켜지 마세요!
DEBUG = True

ALLOWED_HOSTS = []

# 애플리케이션 정의

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'sams',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS 지원
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS 설정 (프론트엔드 도메인에 맞춰 수정)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",                      # 로컬 프론트
    "https://<your-app>.web.app",                 # Firebase Hosting
    "https://<your-app>.firebaseapp.com",
]

# REST_FRAMEWORK = {
#     "DEFAULT_AUTHENTICATION_CLASSES": [
#         "api.auth.FirebaseAuthentication",
#     ],
# }

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # 전역 템플릿 경로 설정
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# 데이터베이스
# 문서: https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# 비밀번호 검증
# 문서: https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 국제화 설정
# 문서: https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = False


# 정적 파일 (CSS, JavaScript, 이미지)
# 문서: https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

# 개발 환경에서는 기본 Django 정적 파일 서빙 사용
# 프로덕션 배포 시에만 whitenoise 사용

# 기본 기본키 필드 타입
# 문서: https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 로그인 관련 설정 (홈 숨김: 로그인 시 실시간 대시보드로 이동)
LOGIN_REDIRECT_URL = '/realtime/'
LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/'
